// src/renderer/types/account.ts
export interface AccountInfo {
  provider: string; // "google" | "box" | "dropbox" | ...
  id: string; // email, login, userId...
  displayName?: string; // Tên hiển thị
}
