name: Build/release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write
    packages: write
    actions: read

jobs:
    release:
        permissions:
            contents: write

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.GITHUB_TOKEN }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # release the app after building
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}

            - name: Fix chrome-sandbox permissions
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo chown root:root dist/linux-unpacked/chrome-sandbox
                  sudo chmod 4755 dist/linux-unpacked/chrome-sandbox
