name: Release

on:
    push:
        tags:
            - "v*.*.*" # trigger khi push tag kiểu vX.Y.Z

jobs:
    release:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # hoặc version bạn đang dùng

            - name: Install dependencies
              run: npm ci # hoặc yarn install

            - name: Build & Publish
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  case "${RUNNER_OS}" in
                    Windows)
                      npx electron-builder --windows --publish always
                      ;;
                    macOS)
                      npx electron-builder --mac --publish always
                      ;;
                    Linux)
                      npx electron-builder --linux --publish always
                      ;;
                  esac
